# Generated by Django 3.1 on 2020-08-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidades',
            options={'managed': False, 'verbose_name': '01.Cad.Cidade'},
        ),
        migrations.AlterModelOptions(
            name='doencas',
            options={'managed': False, 'verbose_name': '01.Cad.Doenca'},
        ),
        migrations.AlterModelOptions(
            name='hospitais',
            options={'managed': False, 'verbose_name': '01.Cad.Hospital'},
        ),
        migrations.AlterModelOptions(
            name='registros',
            options={'managed': False, 'verbose_name': '01.Cad.Registro'},
        ),
    ]
